### ISSUE TITLE
Sign fwupd installs

### ISSUE THREAD

**Issue by KenMacD** [gdamjan/secure-boot#8]
`fwupd` requires `/usr/lib/fwupd/efi/fwupdx64.efi.signed` to work. It would be helpful if the signing of this package was added.

**Comment by gdamjan** [comment]
I use fwupd too. I used this command to sign it:
```
sudo sbsign --key /etc/secure-boot/db.key --cert /etc/secure-boot/db.crt -o /usr/lib/fwupd/efi/fwupdx64.efi.signed /usr/lib/fwupd/efi/fwupdx64.efi
```

any suggestions what level of integration you'd like? I could add a `secure-boot fwupd` or?

**Comment by KenMacD** [comment]
Thank you, It's now signed, but I know I'm going to forget to sign the new version when it's updated, so I was mainly looking for a pacman hook.

**Comment by gdamjan** [comment]
I guess it doesn't hurt to add the hook in the package

**Comment by gdamjan** [comment]
something like this?
https://github.com/gdamjan/secure-boot/commit/813db2467ca2aa8b7a98c5990cabf9729adb713d

**Comment by KenMacD** [comment]
Looks great to me!

**Comment by gdamjan** [comment]
Sorry for out-of-date aur version, I'm trying to consolidate the master branch here, and the AUR branch there. not the easiest thing to do :/
